# Generated by Django 5.2.9 on 2025-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_weekly_reminder',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_product_updates',
            field=models.BooleanField(default=False, help_text='Opt-in for daily check-in reminders'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_daily_reminder',
            field=models.BooleanField(default=False, help_text='Opt-in for weekly reflection reminders'),
        ),
    ]
