# Generated by Django 5.2.9 on 2025-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_email_weekly_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_daily_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_product_updates',
            field=models.BooleanField(default=False),
        ),
    ]
