# Generated by Django 5.2.9 on 2026-01-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_email_daily_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_past_submissions',
            field=models.BooleanField(default=False, help_text='Toggle to view all past cohort tasks/submissions in the dashboard.'),
        ),
    ]
