# Generated by Django 5.2.8 on 2025-11-05 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_1to5', models.IntegerField(help_text='Mood rating from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('baseline_screentime_min', models.IntegerField(help_text='Baseline daily screen time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('intention_text', models.TextField(help_text='Why are you interested in participating?')),
                ('challenge_text', models.TextField(blank=True, help_text='Name one thing you would like to reclaim')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_surveys', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='ExitSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_1to5', models.IntegerField(help_text='Final mood rating from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('final_screentime_min', models.IntegerField(help_text='Final daily screen time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('wins_text', models.TextField(help_text='What were your wins?')),
                ('insight_text', models.TextField(help_text='What insights did you gain?')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_surveys', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'cohort')},
            },
        ),
    ]
