# Generated by Django 5.2.8 on 2025-12-05 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_taskscheduler'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="A unique slug for identifying the survey type (e.g., 'entry', 'daily-checkin').", max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('title_template', models.CharField(blank=True, default='{survey_name}', help_text='A template for the page title. Available placeholders: {survey_name}, {due_date}, {week_number}.', max_length=255)),
                ('purpose', models.CharField(choices=[('GENERIC', 'Generic'), ('ENTRY', 'Entry Survey'), ('EXIT', 'Exit Survey'), ('DAILY_CHECKIN', 'Daily Check-in'), ('WEEKLY_REFLECTION', 'Weekly Reflection')], default='GENERIC', help_text='The role of this survey in the cohort lifecycle.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exitsurvey',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exitsurvey',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='exitsurvey',
            name='user',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique key for this question within the survey. May be used in templates.', max_length=100)),
                ('text', models.CharField(help_text='The question text presented to the user.', max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text Area (multi-line)'), ('integer', 'Integer'), ('radio', 'Radio Select')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which the question appears in the survey.')),
                ('is_required', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, help_text="JSON object for choices if question_type is 'radio'.", null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['survey', 'order'],
                'unique_together': {('survey', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='The specific due date of the task this submission fulfills.', null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to='cohorts.cohort')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveysubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='EntrySurvey',
        ),
        migrations.DeleteModel(
            name='ExitSurvey',
        ),
    ]
