# Generated by Django 5.2.8 on 2025-11-08 10:05

from django.db import migrations
from cohorts.seed import seed_surveys


def create_surveys_and_questions(apps, schema_editor):
    """Create the Survey and Question objects from the definitions above."""
    # The `update=False` flag will use `get_or_create` which is appropriate for a migration.
    for survey, created in seed_surveys(apps=apps, update=False):
        if created:
            print(f'Created Survey: "{survey.name}"')


class Migration(migrations.Migration):
    dependencies = [
        ('cohorts', '0001_initial'), # Ensure cohorts is loaded
        ('surveys', '0002_survey_alter_exitsurvey_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_surveys_and_questions),
    ]
