# Generated by Django 5.2.8 on 2025-12-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_add_survey_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysubmission',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='surveysubmission',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='surveysubmission',
            name='user',
        ),
    ]
