# Generated by Django 5.2.9 on 2025-12-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveysubmission_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section header. Questions with the same section are grouped together visually.', max_length=200),
        ),
    ]
