# Generated by Django 5.2.9 on 2025-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_add_section_to_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text Area (multi-line)'), ('integer', 'Integer'), ('radio', 'Radio Select'), ('info', 'Information (display only)')], default='text', max_length=20),
        ),
    ]
