# Generated by Django 5.2.9 on 2025-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_add_info_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='The question text presented to the user.', max_length=1000),
        ),
    ]
