# Generated by Django 5.2.9 on 2025-12-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='The question text presented to the user.', max_length=3000),
        ),
    ]
