# Generated by Django 5.2.9 on 2025-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text Area (multi-line)'), ('float', 'Float'), ('decimal', 'Decimal'), ('radio', 'Radio Select'), ('info', 'Information (display only)')], default='text', max_length=20),
        ),
    ]
