# Generated by Django 5.2.9 on 2025-12-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_question_question_type'),
        ('cohorts', '0011_cohort_onboarding_survey_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text Area (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('radio', 'Radio Select'), ('info', 'Information (display only)')], default='text', max_length=20),
        ),
    ]
