# Generated by Django 5.2.9 on 2025-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_remove_survey_purpose_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete the survey in minutes.', null=True),
        ),
    ]
