# Generated by Django 5.2.9 on 2026-01-02 18:36

import django.db.models.deletion
from django.db import migrations, models


def migrate_question_sections(apps, schema_editor):
    """
    - Creates SurveySection objects from the old `section` CharField on Question.
    - Populates the new `question.section_fk` field.
    - Converts the first 'info' question of a section into the section's description
      and deletes the original 'info' question.
    """
    Question = apps.get_model('surveys', 'Question')
    SurveySection = apps.get_model('surveys', 'SurveySection')
    Survey = apps.get_model('surveys', 'Survey')
    db_alias = schema_editor.connection.alias

    for survey in Survey.objects.using(db_alias).all():
        # Get unique section titles for this survey, ordered to process consistently.
        section_titles = list(
            survey.questions.exclude(section__exact='')
            .exclude(section__isnull=True)
            .values_list('section', flat=True)
            .distinct()
            .order_by('section')
        )

        for title in section_titles:
            questions_in_section = survey.questions.filter(section=title).order_by('order')
            
            # Evaluate to list to iterate and check first item without multiple queries
            all_questions = list(questions_in_section)

            if not all_questions:
                continue

            description_parts = []
            questions_to_delete = []
            
            for question in all_questions:
                if question.question_type == 'info':
                    description_parts.append(question.text)
                    questions_to_delete.append(question)
                else:
                    break
            
            description = "<br><br>".join(description_parts)

            # Create the SurveySection.
            section, created = SurveySection.objects.using(db_alias).get_or_create(
                survey=survey,
                title=title,
                defaults={'order': all_questions[0].order, 'description': description},
            )
            # If section already existed, but we have a description to add.
            if not created and description and not section.description:
                section.description = description
                section.save(using=db_alias)

            # Associate all questions in this section with the new SurveySection object.
            questions_in_section.update(section_fk=section)

            # If 'info' questions were converted, delete them.
            for q in questions_to_delete:
                q.delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('surveys', '0011_survey_estimated_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section header. Questions with the same section are grouped together visually.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for the section.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which the section appears in the survey.')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey')),
            ],
            options={
                'ordering': ['survey', 'order'],
                'unique_together': {('survey', 'title')},
            },
        ),
        # 2. Add a temporary ForeignKey to the Question model to hold the new relation.
        migrations.AddField(
            model_name='question',
            name='section_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_temp', to='surveys.surveysection'),
        ),
        # 3. Run the data migration to populate SurveySection and the temporary FK.
        migrations.RunPython(migrate_question_sections, migrations.RunPython.noop),
        # 4. Remove the old 'section' CharField.
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        # 5. Rename the temporary FK to 'section'.
        migrations.RenameField(
            model_name='question',
            old_name='section_fk',
            new_name='section',
        ),
        # 6. Update the field to its final state (changing related_name).
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveysection'),
        ),
    ]
