# Generated by Django 5.2.9 on 2026-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_question_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='strength',
            field=models.CharField(blank=True, choices=[('info', 'Information'), ('warn', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], max_length=20, null=True),
        ),
    ]
