# Generated by Django 5.2.8 on 2025-11-07 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='cohort',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this cohort requires payment'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_seats',
            field=models.IntegerField(blank=True, help_text='Maximum number of seats (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cohort',
            name='minimum_price_cents',
            field=models.IntegerField(default=1000, help_text='Minimum price in cents (e.g., 1000 = $10.00)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid_cents',
            field=models.IntegerField(blank=True, help_text='Amount paid in cents (null if free or pending)', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free'), ('refunded', 'Refunded')], default='pending', help_text='Enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed (null if free or pending)', null=True),
        ),
    ]
