# Generated by Django 5.2.8 on 2025-12-05 00:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_remove_cohort_price_cents_cohort_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title_template', models.CharField(blank=True, help_text='Template for the task title. Placeholders: {survey_name}, {week_number}, {due_date}. If blank, survey name is used.', max_length=200)),
                ('task_description_template', models.TextField(blank=True, help_text='Template for the task description. Placeholders: {survey_name}, {week_number}, {due_date}. If blank, survey description is used.')),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], help_text='How often the task repeats.', max_length=20)),
                ('is_cumulative', models.BooleanField(default=False, help_text='If true, missed tasks will accumulate over time.')),
                ('day_of_week', models.IntegerField(blank=True, help_text='For WEEKLY frequency (0=Sunday, 1=Monday, ..., 6=Saturday).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('offset_days', models.IntegerField(blank=True, help_text='For ONCE frequency. The number of days to offset from the start/end date.', null=True)),
                ('offset_from', models.CharField(blank=True, choices=[('start', 'From Cohort Start'), ('end', 'From Cohort End')], help_text='For ONCE frequency. The reference point for the offset.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(help_text='The cohort this schedule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='task_schedulers', to='cohorts.cohort')),
            ],
            options={
                'ordering': ['cohort', 'frequency'],
            },
        ),
    ]
