# Generated by Django 5.2.8 on 2025-12-05 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_taskscheduler'),
        ('surveys', '0002_survey_alter_exitsurvey_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscheduler',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='surveys.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='taskscheduler',
            unique_together={('cohort', 'survey')},
        ),
    ]
