# Generated by Django 5.2.9 on 2025-12-08 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_usersurveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscheduler',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='For WEEKLY frequency (0=Monday, 1=Tuesday, ..., 6=Sunday).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
