# Generated by Django 5.2.9 on 2025-12-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0006_alter_taskscheduler_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='enrollment_end_date',
            field=models.DateField(blank=True, help_text='The last day users can join the cohort.', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='enrollment_start_date',
            field=models.DateField(blank=True, help_text='The first day users can join the cohort.', null=True),
        ),
    ]
