# Generated by Django 5.2.9 on 2025-12-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_add_email_send_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscheduler',
            name='offset_from',
            field=models.CharField(blank=True, choices=[('COHORT_START', 'From Cohort Start'), ('COHORT_END', 'From Cohort End')], help_text='For ONCE frequency. The reference point for the offset.', max_length=50, null=True),
        ),
    ]
