# Generated by Django 5.2.9 on 2025-12-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0009_alter_taskscheduler_offset_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscheduler',
            name='offset_from',
            field=models.CharField(blank=True, choices=[('ENROLL_START', 'From Enrollment Start'), ('ENROLL_END', 'From Enrollment End'), ('COHORT_START', 'From Cohort Start'), ('COHORT_END', 'From Cohort End')], help_text='For ONCE frequency. The reference point for the offset.', max_length=50, null=True),
        ),
    ]
