# Generated by Django 5.2.9 on 2025-12-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0010_alter_taskscheduler_offset_from'),
        ('surveys', '0009_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='onboarding_survey',
            field=models.ForeignKey(blank=True, help_text='The survey presented during onboarding (e.g. Entry Survey).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_cohorts', to='surveys.survey'),
        ),
    ]
