# Generated by Django 5.2.9 on 2025-12-26 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta


def populate_scheduler_slugs(apps, schema_editor):
    """Populate TaskScheduler.slug from survey.slug."""
    TaskScheduler = apps.get_model('cohorts', 'TaskScheduler')

    for scheduler in TaskScheduler.objects.select_related('survey').all():
        scheduler.slug = scheduler.survey.slug
        scheduler.save(update_fields=['slug'])


def calculate_task_instance_id(scheduler, due_date):
    """
    Calculate task_instance_id from due_date based on scheduler frequency.
    
    For ONCE: Always 0
    For DAILY: Day offset from cohort start
    For WEEKLY: Week index
    """
    cohort = scheduler.cohort
    
    if scheduler.frequency == 'ONCE':
        return 0
    elif scheduler.frequency == 'DAILY':
        return (due_date - cohort.start_date).days
    elif scheduler.frequency == 'WEEKLY':
        # Find which week this due_date falls into
        target_weekday = scheduler.day_of_week
        days_until_first = (target_weekday - cohort.start_date.weekday() + 7) % 7
        first_due_date = cohort.start_date + timedelta(days=days_until_first)
        
        if due_date < first_due_date:
            return 0
        
        weeks_diff = (due_date - first_due_date).days // 7
        return weeks_diff
    else:
        # Fallback: use day offset
        return (due_date - cohort.start_date).days


def migrate_usersurveyresponse_data(apps, schema_editor):
    """
    Migrate UserSurveyResponse from due_date to scheduler + task_instance_id.
    
    For each response:
    1. Find the scheduler based on cohort + survey
    2. Calculate task_instance_id from due_date
    3. Set both fields
    """
    UserSurveyResponse = apps.get_model('cohorts', 'UserSurveyResponse')
    TaskScheduler = apps.get_model('cohorts', 'TaskScheduler')
    
    for response in UserSurveyResponse.objects.select_related('submission__survey', 'cohort').all():
        survey = response.submission.survey
        cohort = response.cohort
        due_date = response.due_date
        
        # Find the scheduler (assuming one scheduler per cohort+survey)
        scheduler = TaskScheduler.objects.filter(
            cohort=cohort,
            survey=survey
        ).first()
        
        if scheduler and due_date:
            # Calculate task_instance_id from due_date
            task_instance_id = calculate_task_instance_id(scheduler, due_date)
            
            response.scheduler = scheduler
            response.task_instance_id = task_instance_id
            response.save(update_fields=['scheduler', 'task_instance_id'])
        elif scheduler:
            # No due_date, default to 0
            response.scheduler = scheduler
            response.task_instance_id = 0
            response.save(update_fields=['scheduler', 'task_instance_id'])
        # If no scheduler found, leave as NULL (will be handled by making fields non-nullable)


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0011_cohort_onboarding_survey_purpose'),
        ('surveys', '0010_remove_survey_purpose_alter_question_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # === Part 1: Add TaskScheduler.slug ===
        migrations.AlterUniqueTogether(
            name='taskscheduler',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='slug',
            field=models.SlugField(
                null=True,
                blank=True,
                help_text="URL-friendly identifier for this task (e.g., 'daily-checkin', 'week-1-reflection'). Unique within cohort.",
                max_length=200
            ),
        ),
        migrations.RunPython(populate_scheduler_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='taskscheduler',
            name='slug',
            field=models.SlugField(
                help_text="URL-friendly identifier for this task (e.g., 'daily-checkin', 'week-1-reflection'). Unique within cohort.",
                max_length=200
            ),
        ),
        migrations.AlterUniqueTogether(
            name='taskscheduler',
            unique_together={('cohort', 'slug'), ('cohort', 'survey')},
        ),

        # === Part 2: Refactor UserSurveyResponse ===
        # Step 1: Add new fields as nullable
        migrations.AddField(
            model_name='usersurveyresponse',
            name='scheduler',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responses',
                to='cohorts.taskscheduler'
            ),
        ),
        migrations.AddField(
            model_name='usersurveyresponse',
            name='task_instance_id',
            field=models.IntegerField(
                null=True,
                help_text="Sequential instance number for this scheduler's tasks (0-indexed)."
            ),
        ),

        # Step 2: Migrate data from due_date to scheduler + task_instance_id
        migrations.RunPython(migrate_usersurveyresponse_data, migrations.RunPython.noop),

        # Step 3: Change submission to OneToOne
        migrations.AlterField(
            model_name='usersurveyresponse',
            name='submission',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_response',
                to='surveys.surveysubmission'
            ),
        ),

        # Step 4: Remove due_date field
        migrations.RemoveField(
            model_name='usersurveyresponse',
            name='due_date',
        ),

        # Step 5: Make new fields non-nullable
        migrations.AlterField(
            model_name='usersurveyresponse',
            name='scheduler',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responses',
                to='cohorts.taskscheduler'
            ),
        ),
        migrations.AlterField(
            model_name='usersurveyresponse',
            name='task_instance_id',
            field=models.IntegerField(
                help_text="Sequential instance number for this scheduler's tasks (0-indexed)."
            ),
        ),

        # Step 6: Add unique constraint
        migrations.AlterUniqueTogether(
            name='usersurveyresponse',
            unique_together={('user', 'cohort', 'scheduler', 'task_instance_id')},
        ),
    ]

