# Generated by Django 5.2.8 on 2025-11-05 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood_1to5', models.IntegerField(help_text='How do you feel today? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('digital_satisfaction_1to5', models.IntegerField(help_text='Satisfaction with your digital use today (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('screentime_min', models.IntegerField(help_text='Screen time in minutes (estimated or actual)', validators=[django.core.validators.MinValueValidator(0)])),
                ('proud_moment_text', models.TextField(help_text="One thing you're proud of doing that replaced scrolling")),
                ('digital_slip_text', models.TextField(blank=True, help_text='If you slipped into digital use in any way, how? (optional)')),
                ('reflection_text', models.TextField(help_text='1-2 sentences about how today went')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'cohort', 'date'], name='checkins_da_user_id_980226_idx')],
                'unique_together': {('user', 'cohort', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.IntegerField(help_text='Week number (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('goal_text', models.TextField(help_text="What's your intention for this week?")),
                ('reflection_text', models.TextField(blank=True, help_text='Optional reflection on last week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reflections', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_index'],
                'indexes': [models.Index(fields=['user', 'cohort', 'week_index'], name='checkins_we_user_id_caecd4_idx')],
                'unique_together': {('user', 'cohort', 'week_index')},
            },
        ),
    ]
